pipeline {
  agent {
    dockerfile {
      dir 'automation'
      filename 'Dockerfile'
      args '-v /tools/Xilinx:/tools/Xilinx:ro'
    }
  }
  environment {
    // Xilinx tools have to be mounted from the build server.
    XILINX = '/tools/Xilinx'
    XSDK = "$XILINX/SDK/2018.3"
    // HOME defaults to '/' for some reason.
    HOME = "$WORKSPACE"
    // Extract concise branch name.
    BRANCH = GIT_BRANCH.substring(GIT_BRANCH.lastIndexOf('/') + 1, GIT_BRANCH.length())
  }
  parameters {
    booleanParam(name: 'clean', description: 'Clean workspace instead of build')
  }
  stages {
    stage('clean') {
      when {
        expression { params.clean }
      }
      steps {
        echo "Cleaning branch ${env.BRANCH}"
        cleanWs()
      }
    }
    stage('download') {
      when {
        expression { !params.clean }
      }
      steps {
        echo "Building branch ${env.BRANCH}"
        echo "Commit ${env.GIT_COMMIT}"
        echo "Previously built ${env.GIT_PREVIOUS_COMMIT}"
        sh 'scripts/download-xilinx-uboot.sh'
      }
    }
    stage('build') {
      when {
        expression { !params.clean }
      }
      steps {
        sh 'scripts/build.sh'
      }
    }
    stage('upload') {
      when {
        expression { !params.clean }
      }
      steps {
        script {
          def artifacts = [
            ['u-boot.elf', 'u-boot.elf'],
            ['qdevil.h', 'include/configs/qdevil.h'],
            ['te820-config', '.config']
          ]
          artifacts.each {
            withAWS(credentials:'qdevil-aws-token', region:'eu-west-1') {
              s3Upload(
                file: "u-boot-xlnx/${it[1]}",
                bucket: 'qdevil-artifacts',
                path: "uboot/${env.BRANCH}/${it[0]}",
                metadatas: ["repo:${env.JOB_NAME}", "branch:${env.BRANCH}", "commit:${env.GIT_COMMIT}"]
              )
            }
          }
        }
      }
    }
  }
  post {
    success {
      slackSend(
        color: 'good',
        message: "${env.JOB_NAME} (branch ${env.BRANCH}) succeeded"
      )
    }
    failure {
      slackSend(
        color: 'bad',
        message: "${env.JOB_NAME} (branch ${env.BRANCH}) build ${env.BUILD_NUMBER} FAILED (<${env.BUILD_URL}/console|Output>)"
      )
    }
    changed {
      slackSend(
        channel: 'ci-change',
        color: (currentBuild.result == 'SUCCESS') ? 'good' : 'bad',
        message: "${env.JOB_NAME} (branch ${env.BRANCH}) build ${env.BUILD_NUMBER} changed to ${currentBuild.result}"
      )
    }
  }
}
